name: hscaffold
version: '0.4.4.0'
synopsis: Very simple file/directory structure scaffolding writer monad EDSL
description: '
	See our README on GitHub at <https://github.com/yamadapc/hscaffold>
'
category: Development
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
license: MIT
github: yamadapc/hscaffold

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4.8 && <4.9
- text
- mtl
- transformers
- directory
- filepath
- unix
- regex-compat
- temporary
- exceptions

library:
  source-dirs: src

executables:
  hsfiles-from-directory:
    main: HsfilesFromDirectory.hs
    source-dirs: bin
    dependencies:
    - hscaffold

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - hscaffold
    - QuickCheck
